export enum NotificationType {
    REQUEST_ACTIVATION,
    REQUEST_ALTERNATIVE_CONTACT,
    REQUEST_RESET,
    RESET_SUCCESS,
    REQUEST_JOB,
    REQUEST_ADMIN_ACTIVATION,
    REQUEST_UNKNOWN_INSTITUTE,
    NOTIFICATION_ADMIN_ACTIVATION,
    NOTIFICATION_NOT_ADMIN_ACTIVATED,
    NOTIFICATION_ALREADY_REGISTERED,
    REMINDER_ADMIN_ACTIVATION,
    NOTIFICATION_SENT
}
